name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:          
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 2222
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd cicd-test2
            export KUBECONFIG=/etc/kubernetes/admin.conf
            
            kubectl delete pipelinerun git-clone-build-pipelinerun
            kubectl apply -f git-clone-build-pipelinerun.yaml
